name: AutoOPE-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.9
  - pytorch>=2.0
  - pytorch-cuda>=12.1
  - torchvision
  - torchaudio
  - scikit-optimize
  - lightgbm
  - matplotlib<3.9
  - pip
  - pip:
    - obp
    - ucimlrepo