name: AutoOPE-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.9
  - pytorch::pytorch<=1.13.1
  - torchvision
  - torchaudio
  - scikit-optimize
  - lightgbm
  - matplotlib<3.9
  - pip
  - pip:
    - obp
    - ucimlrepo
    - cvxpy
    - umap-learn